version: 0.2

phases:
  pre_build:
    commands:
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
      - ./sam-installation/install
      - sam --version
  build:
    commands:
      - echo 'Building...'
      - sam build
      - sam deploy --stack-name cicd-sam--${STAGE} --s3-bucket cicd-sam--${STAGE} --capabilities CAPABILITY_IAM --region ap-northeast-1