version: 0.2

phases:
  build:
    commands:
      - echo 'Building...'
      - export BUCKET="cicd-sam-20210519"
      - aws cloudformation package --force-upload --template-file template.yaml --s3-bucket $BUCKET  --output-template template-export.yaml
      - aws cloudformation deploy --template-file template-export.yaml --stack-name stack-cicd-sam-20210519 --capabilities "CAPABILITY_IAM" --region ap-northeast-1
  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name "stack-cicd-sam-20210519" --query 'Stacks[]'