version: 0.2

phases:
  pre_build:
    commands:
      - wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      - unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      - ./sam-installation/install
      - sam --version
  build:
    commands:
      - echo 'Building...'
      - sam build
      - sam deploy --capabilities CAPABILITY_IAM --region ap-northeast-1
  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name "stack-cicd-sam-20210519" --query 'Stacks[]'