version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-0522"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eq8ej2shdznk"
s3_prefix = "sam-app-0522"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prd\""
